[theme]
primaryColor = "#D4AF37"
backgroundColor = "#090D16"
secondaryBackgroundColor = "#111726"
textColor = "#F1F5F9"
font = "sans serif"

[client]
showErrorDetails = false

[ui]
hideTopBar = false
